package org.abos.mc.gs.registry;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.storage.loot.LootTable;
import org.abos.mc.gs.GnomeSupremacy;

public interface GsLootTables {

    String OVERWORLD_MINER1_LOC = "gnome/minecraft/iron_pickaxe/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_MINER1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_MINER1_LOC));
    String OVERWORLD_MINER2_LOC = "gnome/minecraft/iron_pickaxe/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_MINER2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_MINER2_LOC));
    String OVERWORLD_MINER3_LOC = "gnome/minecraft/iron_pickaxe/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_MINER3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_MINER3_LOC));
    String OVERWORLD_EXCAVATOR1_LOC = "gnome/minecraft/iron_shovel/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_EXCAVATOR1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_EXCAVATOR1_LOC));
    String OVERWORLD_EXCAVATOR2_LOC = "gnome/minecraft/iron_shovel/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_EXCAVATOR2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_EXCAVATOR2_LOC));
    String OVERWORLD_EXCAVATOR3_LOC = "gnome/minecraft/iron_shovel/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_EXCAVATOR3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_EXCAVATOR3_LOC));
    String OVERWORLD_FISHER1_LOC = "gnome/minecraft/fishing_rod/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_FISHER1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_FISHER1_LOC));
    String OVERWORLD_FISHER2_LOC = "gnome/minecraft/fishing_rod/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_FISHER2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_FISHER2_LOC));
    String OVERWORLD_FISHER3_LOC = "gnome/minecraft/fishing_rod/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_FISHER3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_FISHER3_LOC));
    String OVERWORLD_LUMBERJACK1_LOC = "gnome/minecraft/iron_axe/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_LUMBERJACK1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_LUMBERJACK1_LOC));
    String OVERWORLD_LUMBERJACK2_LOC = "gnome/minecraft/iron_axe/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_LUMBERJACK2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_LUMBERJACK2_LOC));
    String OVERWORLD_LUMBERJACK3_LOC = "gnome/minecraft/iron_axe/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_LUMBERJACK3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_LUMBERJACK3_LOC));
    String OVERWORLD_SHEPHERD1_LOC = "gnome/minecraft/shears/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_SHEPHERD1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_SHEPHERD1_LOC));
    String OVERWORLD_SHEPHERD2_LOC = "gnome/minecraft/shears/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_SHEPHERD2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_SHEPHERD2_LOC));
    String OVERWORLD_SHEPHERD3_LOC = "gnome/minecraft/shears/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_SHEPHERD3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_SHEPHERD3_LOC));
    String OVERWORLD_MONSTER_HUNTER1_LOC = "gnome/minecraft/iron_sword/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_MONSTER_HUNTER1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_MONSTER_HUNTER1_LOC));
    String OVERWORLD_MONSTER_HUNTER2_LOC = "gnome/minecraft/iron_sword/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_MONSTER_HUNTER2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_MONSTER_HUNTER2_LOC));
    String OVERWORLD_MONSTER_HUNTER3_LOC = "gnome/minecraft/iron_sword/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_MONSTER_HUNTER3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_MONSTER_HUNTER3_LOC));
    String OVERWORLD_ARCHAEOLOGIST1_LOC = "gnome/minecraft/brush/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_ARCHAEOLOGIST1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_ARCHAEOLOGIST1_LOC));
    String OVERWORLD_ARCHAEOLOGIST2_LOC = "gnome/minecraft/brush/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_ARCHAEOLOGIST2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_ARCHAEOLOGIST2_LOC));
    String OVERWORLD_ARCHAEOLOGIST3_LOC = "gnome/minecraft/brush/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_ARCHAEOLOGIST3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_ARCHAEOLOGIST3_LOC));
    String OVERWORLD_DEEP_SEA_DRIVER1_LOC = "gnome/minecraft/trident/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_DEEP_SEA_DRIVER1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_DEEP_SEA_DRIVER1_LOC));
    String OVERWORLD_DEEP_SEA_DRIVER2_LOC = "gnome/minecraft/trident/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_DEEP_SEA_DRIVER2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_DEEP_SEA_DRIVER2_LOC));
    String OVERWORLD_DEEP_SEA_DRIVER3_LOC = "gnome/minecraft/trident/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_DEEP_SEA_DRIVER3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_DEEP_SEA_DRIVER3_LOC));
    String OVERWORLD_RANCHER1_LOC = "gnome/minecraft/lead/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_RANCHER1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_RANCHER1_LOC));
    String OVERWORLD_RANCHER2_LOC = "gnome/minecraft/lead/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_RANCHER2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_RANCHER2_LOC));
    String OVERWORLD_RANCHER3_LOC = "gnome/minecraft/lead/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_RANCHER3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_RANCHER3_LOC));
    String OVERWORLD_FARMER1_LOC = "gnome/minecraft/iron_hoe/overworld/tier1";
    ResourceKey<LootTable> OVERWORLD_FARMER1 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_FARMER1_LOC));
    String OVERWORLD_FARMER2_LOC = "gnome/minecraft/iron_hoe/overworld/tier2";
    ResourceKey<LootTable> OVERWORLD_FARMER2 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_FARMER2_LOC));
    String OVERWORLD_FARMER3_LOC = "gnome/minecraft/iron_hoe/overworld/tier3";
    ResourceKey<LootTable> OVERWORLD_FARMER3 = ResourceKey.create(Registries.LOOT_TABLE, ResourceLocation.fromNamespaceAndPath(GnomeSupremacy.MODID, OVERWORLD_FARMER3_LOC));

}
